settings:
  delete_existing: true #새 데이터를 추가하기 전에 기존 데이터를 삭제하려면 true로 설정합니다
  tables:
    - name: user
      count: 5000
    - name: posts
      count: 10000
    - name: comments
      count: 20000
      #필요에 따라 다른 테이블 추가

#settings: 설정 항목을 포함하는 최상위 키입니다.
#delete_existing: true로 설정되어 있으면, 새로운 데이터를 추가하기 전에 기존 데이터를 삭제합니다.
#tables: 데이터베이스 테이블 목록을 정의합니다.
#name: 테이블의 이름을 지정합니다.
#count: 해당 테이블에 추가할 데이터의 개수를 지정합니다.
#예를 들어, 이 설정에 따르면:

#users 테이블에는 5000개의 데이터가 추가됩니다.
#posts 테이블에는 10000개의 데이터가 추가됩니다.
#comments 테이블에는 20000개의 데이터가 추가됩니다.
